# Zizmor configuration file
# See: https://docs.zizmor.sh/configuration/

rules:
  # Ignore artipacked (credential persistence) warnings for Claude Code workflows
  # These workflows require credentials to interact with GitHub (post comments, etc.)
  # and do not upload artifacts, so the risk is mitigated
  artipacked:
    ignore:
      - claude-code-review.yml
      - claude.yml
